package br.unesp.amoraes.dbvis.ui;

import br.unesp.amoraes.dbvis.beans.DatabaseConnectionEntity;
import br.unesp.amoraes.dbvis.dao.DatabaseConnectionDAO;
import br.unesp.amoraes.dbvis.internals.ValueTextItem;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 * UI: Configure database connections with external RDBMSs
 * @author Alessandro Moraes (sanfatec at gmail.com)
 * @since 2013-01-05
 */
public class ConfigureDatabaseWindow extends javax.swing.JDialog {

    private DefaultListModel<ValueTextItem<DatabaseConnectionEntity>> listSavedConnections;
    private DatabaseConnectionEntity databaseConnection;
    private java.awt.Frame parent =  null;
    
    /**
     * Creates new form ConfigureDatabaseWindow
     */
    public ConfigureDatabaseWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        loadSavedConnectionsList();
        this.parent = parent;
        initComponents();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneSavedConnections = new javax.swing.JScrollPane();
        jListSavedConnections = new javax.swing.JList();
        jLabelSavedConnections = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelDriver = new javax.swing.JLabel();
        jTextFieldUrl = new javax.swing.JTextField();
        jLabelURL = new javax.swing.JLabel();
        jComboBoxDriver = new javax.swing.JComboBox();
        jLabelUsername = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonNew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("br/unesp/amoraes/dbvis/ui/Bundle"); // NOI18N
        setTitle(bundle.getString("ConfigureDatabaseWindow.title")); // NOI18N

        jListSavedConnections.setModel(listSavedConnections);
        jListSavedConnections.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListSavedConnections.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListSavedConnectionsValueChanged(evt);
            }
        });
        jScrollPaneSavedConnections.setViewportView(jListSavedConnections);

        jLabelSavedConnections.setText(bundle.getString("ConfigureDatabaseWindow.jLabelSavedConnections.text")); // NOI18N

        jLabelName.setText(bundle.getString("ConfigureDatabaseWindow.jLabelName.text")); // NOI18N

        jLabelDriver.setText(bundle.getString("ConfigureDatabaseWindow.jLabelDriver.text")); // NOI18N

        jLabelURL.setText(bundle.getString("ConfigureDatabaseWindow.jLabelURL.text")); // NOI18N

        jComboBoxDriver.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "org.postgresql.Driver", "com.mysql.jdbc.Driver", "org.sqlite.JDBC" }));

        jLabelUsername.setText(bundle.getString("ConfigureDatabaseWindow.jLabelUsername.text")); // NOI18N

        jLabelPassword.setText(bundle.getString("ConfigureDatabaseWindow.jLabelPassword.text")); // NOI18N

        jButtonSave.setText(bundle.getString("ConfigureDatabaseWindow.jButtonSave.text")); // NOI18N
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonDelete.setText(bundle.getString("ConfigureDatabaseWindow.jButtonDelete.text")); // NOI18N
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonNew.setText(bundle.getString("ConfigureDatabaseWindow.jButtonNew.text")); // NOI18N
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPaneSavedConnections, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUrl)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelName)
                                    .addComponent(jLabelDriver)
                                    .addComponent(jLabelURL)
                                    .addComponent(jComboBoxDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelUsername)
                                    .addComponent(jLabelPassword)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                        .addComponent(jTextFieldUsername, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonSave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonNew)))
                                .addGap(0, 217, Short.MAX_VALUE))))
                    .addComponent(jLabelSavedConnections))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSavedConnections)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneSavedConnections, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDriver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelURL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSave)
                            .addComponent(jButtonDelete)
                            .addComponent(jButtonNew))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        DatabaseConnectionEntity entity = new DatabaseConnectionEntity();
        if(databaseConnection != null && databaseConnection.getId() != null){
            entity.setId(databaseConnection.getId());
        }
        entity.setName(jTextFieldName.getText());
        entity.setDriver(jComboBoxDriver.getSelectedItem().toString());
        entity.setUrl(jTextFieldUrl.getText());
        entity.setUsername(jTextFieldUsername.getText());
        entity.setPassword(jTextFieldPassword.getText());
        DatabaseConnectionDAO.save(entity);
        loadSavedConnectionsList();
        //if main window have list of connections, update
        if(parent instanceof MainWindow){
            MainWindow mainWindow = (MainWindow)parent;
            if(mainWindow.getDataSelectIFrame() != null){
                mainWindow.getDataSelectIFrame().loadSavedConnectionsList();
            }
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        if(databaseConnection != null && databaseConnection.getId() != null){
            DatabaseConnectionDAO.delete(databaseConnection.getId());
            jListSavedConnections.clearSelection();
            loadSavedConnectionsList();
        }
        clearFields(); 
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
         clearFields(); 
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jListSavedConnectionsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListSavedConnectionsValueChanged
        int index = jListSavedConnections.getSelectedIndex();
        if(index != -1){
            DatabaseConnectionEntity entity = listSavedConnections.get(index).getValue();
            databaseConnection = entity;
            jTextFieldName.setText(entity.getName());
            jComboBoxDriver.setSelectedItem(entity.getDriver());
            jTextFieldUrl.setText(entity.getUrl());
            jTextFieldUsername.setText(entity.getUsername());
            jTextFieldPassword.setText(entity.getPassword());
        }
    }//GEN-LAST:event_jListSavedConnectionsValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox jComboBoxDriver;
    private javax.swing.JLabel jLabelDriver;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSavedConnections;
    private javax.swing.JLabel jLabelURL;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JList jListSavedConnections;
    private javax.swing.JScrollPane jScrollPaneSavedConnections;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldUrl;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables

    private void loadSavedConnectionsList() {
         if(listSavedConnections == null){
            listSavedConnections = new DefaultListModel<ValueTextItem<DatabaseConnectionEntity>>();
        }
        listSavedConnections.removeAllElements();
        List<DatabaseConnectionEntity> listConnections = DatabaseConnectionDAO.listAll();
        for(DatabaseConnectionEntity e : listConnections){
            listSavedConnections.addElement(new ValueTextItem(e, e.getName()));
        }
        
    }

    private void clearFields() {
        databaseConnection = null;
        jTextFieldName.setText("");
        jTextFieldUrl.setText("");
        jTextFieldUsername.setText("");
        jTextFieldPassword.setText("");
        jComboBoxDriver.setSelectedIndex(0);
    }
}
