package br.unesp.amoraes.dbvis.ui;

import java.awt.event.MouseEvent;
import javax.swing.JTextPane;
import javax.swing.SwingUtilities;

/**
 * UI: console to show some important information to the application user
 * @author Alessandro Moraes (sanfatec at gmail.com)
 * @since 2013-01-06
 */
public class ConsoleIFrame extends javax.swing.JInternalFrame {

    public static ConsoleIFrame instance = null;
    public static ConsoleIFrame getInstance(){
        if(instance == null)
            instance = new ConsoleIFrame();
        return instance;
    }
    
    /**
     * Creates new form ConsoleIFrame
     */
    private ConsoleIFrame() {
        initComponents();
    }
    
    public JTextPane getJTextPaneConsole(){
        return jTextPaneConsole;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuRightClick = new javax.swing.JPopupMenu();
        jMenuItemClear = new javax.swing.JMenuItem();
        jScrollPaneConsole = new javax.swing.JScrollPane();
        jTextPaneConsole = new javax.swing.JTextPane();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("br/unesp/amoraes/dbvis/ui/Bundle"); // NOI18N
        jMenuItemClear.setText(bundle.getString("ConsoleIFrame.jMenuItemClear.text")); // NOI18N
        jMenuItemClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClearActionPerformed(evt);
            }
        });
        jPopupMenuRightClick.add(jMenuItemClear);

        setMaximizable(true);
        setResizable(true);
        setTitle(bundle.getString("ConsoleIFrame.title")); // NOI18N

        jTextPaneConsole.setEditable(false);
        jTextPaneConsole.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jTextPaneConsole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextPaneConsoleMouseClicked(evt);
            }
        });
        jScrollPaneConsole.setViewportView(jTextPaneConsole);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneConsole, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneConsole, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClearActionPerformed
        this.jTextPaneConsole.setText("");
    }//GEN-LAST:event_jMenuItemClearActionPerformed

    private void jTextPaneConsoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPaneConsoleMouseClicked
        if(SwingUtilities.isRightMouseButton(evt)){
            this.jPopupMenuRightClick.show(jTextPaneConsole, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jTextPaneConsoleMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItemClear;
    private javax.swing.JPopupMenu jPopupMenuRightClick;
    private javax.swing.JScrollPane jScrollPaneConsole;
    private javax.swing.JTextPane jTextPaneConsole;
    // End of variables declaration//GEN-END:variables
}
