/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unesp.amoraes.dbvis.ui;

import br.unesp.amoraes.dbvis.App;
import br.unesp.amoraes.dbvis.KGlobal;
import br.unesp.amoraes.dbvis.beans.DisplayEntity;
import br.unesp.amoraes.dbvis.beans.enums.ProjectType;
import br.unesp.amoraes.dbvis.dao.DisplayDAO;
import br.unesp.amoraes.dbvis.internals.FunctionsHelper;
import br.unesp.amoraes.dbvis.rest.APIServer;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 * UI: The main window with menus and a desktop pane to show all UI windows
 * @author Alessandro Moraes (sanfatec at gmail.com)
 * @since 2013-01-04
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Store if one project is in the editor
     */
    boolean isEditing = false;
    private DataSelectIFrame dataSelectIFrame;
    private JInternalFrame paletteIFrame;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.addWindowListener(new OnCloseWindowListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneMain = new javax.swing.JDesktopPane();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuNew = new javax.swing.JMenu();
        jMenuItemNewGraph = new javax.swing.JMenuItem();
        jMenuItemFileExit = new javax.swing.JMenuItem();
        jMenuConfigure = new javax.swing.JMenu();
        jMenuItemChangePassword = new javax.swing.JMenuItem();
        jMenuItemConfigureDatabaseConnections = new javax.swing.JMenuItem();
        jMenuItemConfigureDisplays = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(KGlobal.APP_NAME);
        setName("mainWindow"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("br/unesp/amoraes/dbvis/ui/Bundle"); // NOI18N
        jMenuFile.setText(bundle.getString("MainWindow.jMenuFile.text")); // NOI18N

        jMenuNew.setText(bundle.getString("MainWindow.jMenuNew.text")); // NOI18N

        jMenuItemNewGraph.setText(bundle.getString("MainWindow.jMenuItemNewGraph.text")); // NOI18N
        jMenuItemNewGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewGraphActionPerformed(evt);
            }
        });
        jMenuNew.add(jMenuItemNewGraph);

        jMenuFile.add(jMenuNew);

        jMenuItemFileExit.setText(bundle.getString("MainWindow.jMenuItemFileExit.text")); // NOI18N
        jMenuItemFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileExit);

        jMenuBarMain.add(jMenuFile);

        jMenuConfigure.setText(bundle.getString("MainWindow.jMenuConfigure.text")); // NOI18N

        jMenuItemChangePassword.setText(bundle.getString("MainWindow.jMenuItemChangePassword.text")); // NOI18N
        jMenuItemChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChangePasswordActionPerformed(evt);
            }
        });
        jMenuConfigure.add(jMenuItemChangePassword);

        jMenuItemConfigureDatabaseConnections.setText(bundle.getString("MainWindow.jMenuItemConfigureDatabaseConnections.text")); // NOI18N
        jMenuItemConfigureDatabaseConnections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConfigureDatabaseConnectionsActionPerformed(evt);
            }
        });
        jMenuConfigure.add(jMenuItemConfigureDatabaseConnections);

        jMenuItemConfigureDisplays.setText(bundle.getString("MainWindow.jMenuItemConfigureDisplays.text")); // NOI18N
        jMenuItemConfigureDisplays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConfigureDisplaysActionPerformed(evt);
            }
        });
        jMenuConfigure.add(jMenuItemConfigureDisplays);

        jMenuBarMain.add(jMenuConfigure);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemConfigureDatabaseConnectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConfigureDatabaseConnectionsActionPerformed
        new ConfigureDatabaseWindow(this,true).setVisible(true);
    }//GEN-LAST:event_jMenuItemConfigureDatabaseConnectionsActionPerformed

    private void jMenuItemNewGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewGraphActionPerformed
        newProject(ProjectType.GRAPH);
    }//GEN-LAST:event_jMenuItemNewGraphActionPerformed

    private void jMenuItemFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFileExitActionPerformed
        WindowEvent windowClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
	this.dispatchEvent(windowClosing);
    }//GEN-LAST:event_jMenuItemFileExitActionPerformed

    private void jMenuItemConfigureDisplaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConfigureDisplaysActionPerformed
        new ConfigureDisplayWindow(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemConfigureDisplaysActionPerformed

    private void jMenuItemChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemChangePasswordActionPerformed
        new PasswordWindow(this,true).setVisible(true);
    }//GEN-LAST:event_jMenuItemChangePasswordActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneMain;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jMenuConfigure;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemChangePassword;
    private javax.swing.JMenuItem jMenuItemConfigureDatabaseConnections;
    private javax.swing.JMenuItem jMenuItemConfigureDisplays;
    private javax.swing.JMenuItem jMenuItemFileExit;
    private javax.swing.JMenuItem jMenuItemNewGraph;
    private javax.swing.JMenu jMenuNew;
    // End of variables declaration//GEN-END:variables

    private void setDefaultPanelsLayout() {
        if(isEditing){
            FunctionsHelper.logOnConsole(FunctionsHelper.getString("MainWindow.message.redefinePanelLayout"));
            dataSelectIFrame.setBounds(0,0,new Double(jDesktopPaneMain.getWidth()*0.7).intValue(), new Double(jDesktopPaneMain.getHeight()*0.8).intValue());
            paletteIFrame.setBounds(new Double(jDesktopPaneMain.getWidth()*0.7).intValue(), 0, new Double(jDesktopPaneMain.getWidth()*0.3).intValue(), new Double(jDesktopPaneMain.getHeight()).intValue());
            ConsoleIFrame.getInstance().setBounds(0, new Double(jDesktopPaneMain.getHeight()*0.8).intValue(), new Double(jDesktopPaneMain.getWidth()*0.7).intValue(), new Double(jDesktopPaneMain.getHeight()*0.2).intValue());
            
        }
    }
    
    private void newProject(ProjectType type){
        if(isEditing){
            
        }else{           
            ConsoleIFrame consoleIFrame = ConsoleIFrame.getInstance();
            jDesktopPaneMain.add(consoleIFrame);
            consoleIFrame.setVisible(true);
            
            if(type.equals(ProjectType.GRAPH)){
                paletteIFrame = new GraphPaletteIFrame();
                
            }
            jDesktopPaneMain.add(paletteIFrame);
            paletteIFrame.setVisible(true);
            ((IPalette)paletteIFrame).disableAllComponents();
            
            dataSelectIFrame = new DataSelectIFrame(this);
            jDesktopPaneMain.add(dataSelectIFrame);
            dataSelectIFrame.setVisible(true);
            
            isEditing = true;
            this.setTitle(KGlobal.APP_NAME+" - "+FunctionsHelper.getString("MainWindow.message.unsavedProject"));

            setDefaultPanelsLayout();
            
            App.setCurrentProjectType(type);
            
           
        }
    }
    
    public IPalette getPalleteIFrame(){
        return (IPalette)paletteIFrame;
    }
    
    public DataSelectIFrame getDataSelectIFrame(){
        return dataSelectIFrame;
    }

   
    
    
    class OnCloseWindowListener extends WindowAdapter {
        public void windowClosing(WindowEvent e) {
            int opt = JOptionPane.showConfirmDialog(e.getWindow(), FunctionsHelper.getString("MainWindow.message.reallyQuit", null), FunctionsHelper.getString("MainWindow.message.quit", null), JOptionPane.YES_NO_OPTION);
            if (opt == JOptionPane.YES_OPTION)
                APIServer.getInstance().stop();
            System.exit(0);
        }
    }
    
}
